### ISSUE TITLE
license field object reference invalid

### ISSUE THREAD

**Issue by RonGonz-illumio** [cpainchaud/pylo#4]
https://github.com/cpainchaud/pylo/blob/b5174a6f3dc59ce5ccb23734fb3664768a32becd/setup.py#L21

changed to 'license' temporarily to bypass setup issue:

```
Obtaining file://C:\Users\ron.gonzalez\PycharmProjects\pylo
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [35 lines of output]
  running egg_info
  creating C:\Users\ron.gonzalez\AppData\Local\Temp\pip-pip-egg-info-chwdya0o\pylo.egg-info
  writing C:\Users\ron.gonzalez\AppData\Local\Temp\pip-pip-egg-info-chwdya0o\pylo.egg-info\PKG-INFO
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\ron.gonzalez\PycharmProjects\pylo\setup.py", line 13, in <module>
      setup(
    File "C:\Users\ron.gonzalez\PycharmProjects\pce_data_populator\311venv\Lib\site-packages\setuptools\__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\ron.gonzalez\PycharmProjects\pce_data_populator\311venv\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "C:\Users\ron.gonzalez\PycharmProjects\pce_data_populator\311venv\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Users\ron.gonzalez\PycharmProjects\pce_data_populator\311venv\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
      self.run_command(cmd)
    File "C:\Users\ron.gonzalez\PycharmProjects\pce_data_populator\311venv\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
      super().run_command(command)
    File "C:\Users\ron.gonzalez\PycharmProjects\pce_data_populator\311venv\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
      cmd_obj.run()
    File "C:\Users\ron.gonzalez\PycharmProjects\pce_data_populator\311venv\Lib\site-packages\setuptools\command\egg_info.py", line 301, in run
      writer(self, ep.name, os.path.join(self.egg_info, ep.name))
    File "C:\Users\ron.gonzalez\PycharmProjects\pce_data_populator\311venv\Lib\site-packages\setuptools\command\egg_info.py", line 675, in write_pkg_info
      metadata.write_pkg_info(cmd.egg_info)
    File "C:\Users\ron.gonzalez\PycharmProjects\pce_data_populator\311venv\Lib\site-packages\setuptools\_distutils\dist.py", line 1136, in write_pkg_info
      self.write_pkg_file(pkg_info)
    File "C:\Users\ron.gonzalez\PycharmProjects\pce_data_populator\311venv\Lib\site-packages\setuptools\dist.py", line 197, in write_pkg_file
      write_field('License', rfc822_escape(license))
                             ^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\ron.gonzalez\PycharmProjects\pce_data_populator\311venv\Lib\site-packages\setuptools\_distutils\util.py", line 511, in rfc822_escape
      lines = header.split('\n')
              ^^^^^^^^^^^^
  AttributeError: '_Printer' object has no attribute 'split'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by cpainchaud** [comment]
thank you for your report! It's now fixed
